#!/system/bin/sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

(
	CORTEX_CHECK=`pgrep -f "/system/bin/sh sh /sbin/ext/cortexbrain-tune.sh" | wc -l`;
	if [ "$CORTEX_CHECK" != 0 ]; then
		echo "SERVICE ONLINE";
	else
		echo "SERVICE OFFLINE";
	fi;
)&
